AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys the Alert Logic Threat/Log Manager Appliance in a VPC

Parameters:
  pInstanceName:
    Type: String
    Description: Name for your new Threat Manager instance
    Default: "Alert Logic Threat Manager Appliance"
  pVpcID:
    Type: AWS::EC2::VPC::Id
    Description: VPC into which Threat Manager will be deployed.
  pMonitoringCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR Block of the VPC to be covered
  pSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: ID of a subnet (preferably private) which Threat Manager appliance will be deployed into.
  pInstanceType:
    Type: String
    Description: EC2 Instance Type Threat Manager will be spun up as.
    Default: c4.large
    AllowedValues:
    # - c3.large
    # - c3.xlarge
    # - c3.2xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
  pAssignPublicIP:
    Type: String
    Description: Does this instance get a Public IP (required if no NatGateway in place)?
    AllowedValues:
      - true
      - false

Outputs:
  agentSecurityGroupID:
    Value: !Ref 'sgThreatManager'
    Description: Copy this Security Group ID into the destination fields of the new egress rules for the Agents' Security Groups.
  TemplateVersion:
    Value: 0.1.1
  ApplianceVersion:
    Value: "Alertlogic TMC - P13"

# Be Sure to update the ApplianceVersion in the output when updating this table!
Mappings:
  ThreatManagerAMI:
    ap-south-1:
      AMI: ami-944916fb
    eu-west-3:
      AMI: ami-2d66d050
    eu-west-2:
      AMI: ami-c66480a1
    eu-west-1:
      AMI: ami-c57336bc
    ap-northeast-2:
      AMI: ami-e768c589
    ap-northeast-1:
      AMI: ami-f07e3896
    sa-east-1:
      AMI: ami-72115a1e
    ca-central-1:
      AMI: ami-6d880f09
    ap-southeast-1:
      AMI: ami-1c1e5560
    ap-southeast-2:
      AMI: ami-3edd1b5c
    eu-central-1:
      AMI: ami-aa92ffc5
    us-east-1:
      AMI: ami-5934df24
    us-east-2:
      AMI: ami-e5fdca80
    us-west-1:
      AMI: ami-87e6ede7
    us-west-2:
      AMI: ami-5b9e1623
    us-gov-west-1:
      AMI: ami-89df5ce8

Resources:
  sgThreatManager:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Alert Logic Threat Manager Security Group
      VpcId: !Ref 'pVpcID'
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: !Ref 'pMonitoringCIDR'
        FromPort: '7777'
        ToPort: '7777'
      - IpProtocol: tcp
        CidrIp: !Ref 'pMonitoringCIDR'
        FromPort: '443'
        ToPort: '443'

      SecurityGroupEgress:
      - IpProtocol: tcp
        CidrIp: 204.110.218.96/27
        FromPort: '443'
        ToPort: '443'
      - IpProtocol: tcp
        CidrIp: 204.110.219.96/27
        FromPort: '443'
        ToPort: '443'
      - IpProtocol: tcp
        CidrIp: 204.110.218.96/27
        FromPort: '4138'
        ToPort: '4138'
      - IpProtocol: tcp
        CidrIp: 204.110.219.96/27
        FromPort: '4138'
        ToPort: '4138'
      - IpProtocol: tcp
        CidrIp: 208.71.209.32/27
        FromPort: '443'
        ToPort: '443'
      - IpProtocol: tcp
        CidrIp: 185.54.124.0/24
        FromPort: '443'
        ToPort: '443'
      - IpProtocol: tcp
        CidrIp: 208.71.209.32/27
        FromPort: '4138'
        ToPort: '4138'
      - IpProtocol: tcp
        CidrIp: 185.54.124.0/24
        FromPort: '4138'
        ToPort: '4138'
      - IpProtocol: udp
        CidrIp: 8.8.8.8/32
        FromPort: '53'
        ToPort: '53'
      - IpProtocol: udp
        CidrIp: 8.8.4.4/32
        FromPort: '53'
        ToPort: '53'
      - IpProtocol: tcp
        CidrIp: 8.8.8.8/32
        FromPort: '53'
        ToPort: '53'
      - IpProtocol: tcp
        CidrIp: 8.8.4.4/32
        FromPort: '53'
        ToPort: '53'

      Tags:
      - Key: Name
        Value: !Join ['', [!Ref 'pInstanceName', ' Security Group']]
      - Key: application
        Value: AlertLogic
      - Key: contact-email
        Value: ISO-CounterThreatUnit@turner.com
      - Key: customer
        Value: turner-iso
      - Key: team
        Value: turner-iso
      - Key: environment
        Value: prod

  instanceTmAppliance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ThreatManagerAMI, !Ref "AWS::Region", "AMI"]
      InstanceType: !Ref 'pInstanceType'
      NetworkInterfaces:
      - GroupSet:
        - !Ref 'sgThreatManager'
        AssociatePublicIpAddress: !Ref pAssignPublicIP
        DeviceIndex: '0'
        DeleteOnTermination: 'true'
        SubnetId: !Ref 'pSubnet'
      Tags:
      - Key: Name
        Value: !Ref 'pInstanceName'
      - Key: application
        Value: AlertLogic
      - Key: contact-email
        Value: ISO-CounterThreatUnit@turner.com
      - Key: customer
        Value: turner-iso
      - Key: team
        Value: turner-iso
      - Key: environment
        Value: prod
    DependsOn: sgThreatManager
