---
Description: Aws CodePipeline
Parameters:
  BucketLocation:
    Type: String
    Default: ""
  Name:
    Type: String
    Default: ""
  Role:
    Type: String
    Default: ""
  StagesName:
    Type: String
    Default: ""
  WebHookName:
    Type: String
    Default: ""


Resources:
  ActionType:
  Type: AWS::CodePipeline::CustomActionType
  Properties:
    Category:
    ConfigurationProperties:
    InputArtfactDetails:
    OutputArtfactDetais:
    Provider:
    Settings:
    Version:
  

Resources:
  Webhook:
  Type: AWS::CodePipeline::WebHook
  Properties:
    Authentication: UNAUTHENTICATED
    # AuthenticationConfiguration:
    #   SecretToken:
    Filters:
      - 
        JsonPath:
        MatchEquals:
    Name: !Ref WebHookName
    TargetPipeline:
    TargetPipelineVersion:

Resources:
  CodePipeline:
  Type: AWS::CodePipeline::Pipeline
  Properties:
    ArtifactStore:
      Location: !Ref BucketLocation
      Type: S3
    Name: !Ref Name
    RestartExecutionOnUpdate: true
    RoleArn: !Ref Role
    DisableInboundStageTransitions:
    Stages:
      - 
        Action:
        Blockers:
        Name: !Ref StagesName
    
