---
Parameters:
  PName: 
    Type: String
    Default: ""
  GName:
    Type: String
    Default: ""

Description: Create iam policy and group.
Resources:
# Criação do Grupo
  IamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GName
      # Policies:
      # - PolicyName: !Ref PName
      #   PolicyDocument: 

# Criação da Policy
  IamPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      Groups:
        - !Ref IamGroup
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "iam:GetAccountPasswordPolicy"
              - "iam:GetAccountSummary"
              - "iam:ListVirtualMFADevices"
            Resource: "*"
          - Effect: "Allow"
            Action: 
              - "iam:GetUser"
              - "iam:ChangePassword"
            Resource: "arn:aws:iam::*:user/${aws:username}"
          - Effect: "Allow"
            Action:  
              - "iam:CreateAccessKey"
              - "iam:ListAccessKeys"
              - "iam:UpdateAccessKey"
              - "iam:DeleteAccessKey"
              - "iam:GetAccessKeyLastUsed"
            Resource: "arn:aws:iam::*:user/${aws:username}"
          - Effect: "Allow"
            Action:
              - "iam:UploadSSHPublicKey"
              - "iam:GetSSHPublicKey"
              - "iam:ListSSHPublicKeys"
              - "iam:DeleteSSHPublicKey"
              - "iam:UpdateSSHPublicKey"
            Resource: "arn:aws:iam::*:user/${aws:username}"
          - Effect: "Allow"
            Action:
              - "iam:CreateVirtualMFADevice"
              - "iam:EnableMFADevice"
              - "iam:DeleteVirtualMFADevice"
              - "iam:ListMFADevices"
              - "iam:ListVirtualMFADevice"
              - "iam:ResyncMFADevices"
              - "iam:DeactivateMFADevice"
              - "iam:GetUser"
            Resource: 
              - "arn:aws:iam::*:user/${aws:username}"
              - "arn:aws:iam::*:mfa/${aws:username}"
          - Effect: "Deny"
            Action:
              - "ec2:*"
              - "codecommit:*"
              - "datapipeline:*"
              - "dynamodb:*"
              - "s3:*"
              - "rds:*"
            Resource: "*"  
      PolicyName: !Ref PName
    DependsOn: IamGroup
  
        
Outputs:
  IamP:
    Description: Name Policy
    Value: !Ref IamPolicy
    Export:
      Name: iam-policy
  IamG:
    Description: Name Group
    Value: !Ref IamGroup
    Export:
      Name: iam-group
        