---
Parameters:
  GName:
    Type: String
    Default: ""
    MaxLength: 48
  
Conditions:
  CreateGroup: !Equals [!Ref GName, ""]

Description: Create iam policy and group.
Resources:
# Criação do Grupo
  IamGroup:
    Condition: CreateGroup
    Type: AWS::IAM::Group
    Properties:
      GroupName: EnableMFA
      

# Criação da Policy
  IamPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      # Groups:
      #   - !Ref IamGroup
      PolicyName: !Sub EnableMFA-${AWS::StackName}
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "iam:GetAccountPasswordPolicy"
              - "iam:ListVirtualMFADevices"
            Resource: "*"
          - Effect: "Allow"
            Action: 
              - "iam:GetUser"
              - "iam:ChangePassword"
            Resource: "arn:aws:iam::*:user/${aws:username}"
          - Effect: "Allow"
            Action:  
              - "iam:*AccessKey*"
              - "iam:GetUser"              
            Resource: "arn:aws:iam::*:user/${aws:username}"
          - Effect: "Allow"
            Action:
              - "iam:*SSHPublicKey*"
              - "iam:GetUser"             
            Resource: "arn:aws:iam::*:user/${aws:username}"
          - Effect: "Allow"
            Action:
              - "iam:*MFADevice*"              
              - "iam:*VirtualMFADevice*"
            Resource: 
              - "arn:aws:iam::*:user/${aws:username}"
              - "arn:aws:iam::*:mfa/${aws:username}"
          - Effect: "Allow"
            Action:
              - "iam:ListMFADevices"
            Resource: 
              - "arn:aws:iam::*:user/${aws:username}"
              - "arn:aws:iam::*:mfa/*"
          - Effect: "Allow"
            Action: 
              - "iam:DeactivateMFADevice"
            Resource:
              - "arn:aws:iam::*:user/${aws:username}"
              - "arn:aws:iam::*:mfa/${aws:username}"
            Condition:
              BoolIfExists:
                "aws:MultiFactorAuthPresent": "true" 
          - Effect: "Deny"
            NotAction:
              - "iam:CreateVirtualMFADevice"
              - "iam:EnableMFADevice"
              - "iam:ListMFADevices"
              - "iam:ListUsers"
              - "iam:ListVirtualMFADevices"
              - "iam:ResyncMFADevice"
            Resource: "*"
            Condition:
              BoolIfExists:
                "aws:MultiFactorAuthPresent": "false"
      Groups:
        - !If [CreateGroup, !Ref IamGroup, !Ref GName] 
        
# Outputs:
#   IamP:
#     Description: Name Policy
#     Value: !Ref IamPolicy
#     Export:
#       Name: iam-policy
  # IamG:
  #   Description: Name Group
  #   Value: !Ref IamGroup
  #   Export:
  #     Name: iam-group
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: User Group Parameters
        Parameters:
          - Gname
        