Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: LG
      ServiceRole: 'arn:aws:iam::240639734538:role/code-build'
      Artifacts:
        ArtifactIdentifier: LG
        EncryptionDisabled: true
        Location: s3-lg
        Name: /
        NamespaceType: NONE
        OverrideArtifactName: false
        Packaging: NONE
        Type: S3
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        ImagePullCredentialsType: CODEBUILD
      Source:
      #   BuildSpec: |
      #     version: 0.2
      #     phases:
      #       post_build:
      #         commands:
      #           - aws s3 sync . s3://s3-lg --exclude '.gitignore' --exclude '.git/*'
        Auth:
          Type: OAUTH
        Type: BITBUCKET
        Location: https://thiagochaves@bitbucket.org/eiplus/eiplus-lg.git
      TimeoutInMinutes: 5
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: BASE_REF
              Pattern: ^refs/heads/master$
          - - Type: EVENT
              Pattern: PUSH, PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED
          
        
          # - Type: BASE_REF
          #   Pattern: ^refs/heads/master$
          #   ExcludeMatchedPattern: false
          # - Type: ACTOR_ACCOUNT_ID
          #   Pattern: 12345
          #   ExcludeMatchedPattern: true
          # - Type: EVENT
          #   Pattern: PUSH
          # - Type: HEAD_REF
          #   Pattern: ^refs/heads/.*
            # - Type: FILE_PATH
            #   Pattern: READ_ME
            #   ExcludeMatchedPattern: true