Description: Aws CodePipeline
Parameters:
  # ServiceRole:
  #   Type: String
  #   Default: ""
  BucketLocation:
    Type: String
    Default: ""
  ArtifactIdentifier:
    Type: String
    Default: ""
  RepositoryLocation:
    Type: String
    Default: ""

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: LG
      ServiceRole: arn:aws:iam::240639734538:role/service-role/codebuild-LG-service-role
      Artifacts:
        ArtifactIdentifier: !Ref ArtifactIdentifier
        EncryptionDisabled: true
        Location: !Ref BucketLocation
        Name: /
        NamespaceType: NONE
        OverrideArtifactName: false
        Packaging: NONE
        Type: S3
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        ImagePullCredentialsType: CODEBUILD
      Source:
        BuildSpec: |
          version: 0.2
          phases:
            post_build:
              commands:
                - aws s3 sync . s3://s3-lg --exclude '.gitignore' --exclude '.git/*'
        Auth:
          Type: OAUTH
        Type: CODECOMMIT
        Location: !Ref RepositoryLocation
      TimeoutInMinutes: 5
      # Triggers:
      #   # Webhook: true
      #   FilterGroups:               
      #     - - Type: HEAD_REF
      #         Pattern: master
      #       - Type: EVENT
      #         Pattern: PUSH
              
              
          
        