Resources:
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: s3-lg
      PolicyDocument:
        Version: "2012-10-17" 
        Statement:
          -
            Effect": "Allow"
            Principal": "*"
            Action": ['s3:*']
            Resource": "*"
              
            
          
          