Parameters:
  NomeRepositorio:
    Type: String
    Default: ""
  DescricaoRepositorio:
    Type: String
    Default: ""

Resources:
  CodeCommitProject:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref NomeRepositorio
      RepositoryDescription: !Ref DescricaoRepositorio    
      